hydra:
  output_subdir: null
  run:
    dir: /network/scratch/j/juan.duque/hydra/

seed: 1
env_type: "cg"
reward_window: 7
grad_max_norm: 1
evaluate_every: 50
evaluation_steps: 50
wandb_dir: /network/scratch/j/juan.duque/wandb/
reset_every: 1000
target_update: 10
milestones: [200, 400]
entropy_weight: 0.07
env:
  max_steps: 50
  split_coins: False
  grid_size: 3
base_agent:
  gamma: 0.95
  opt_type: "adam"
  critic_opt_type: "adam"
  exp_opt_type: "eg"
  other_opt_type: "adam"
vip_agent:
  optim_config:
    lr: 0.0002
    momentum: 0.9
    weight_decay: 0
    beta_1: 0.9
    beta_2: 0.999
  critic_optim_config:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0
    beta_1: 0.9
    beta_2: 0.999
  batch_size: 8000
  rollout_len: 50
  hidden_size: 64
  entropy_weight: 1
  inf_weight: 0.4