hydra:
  output_subdir: null
  run:
    dir: /network/scratch/j/juan.duque/hydra/

seed: 7
reward_window: 7
num_episodes: 1000000
sp_weight: 1
kl_weight: 0
grad_max_norm: 1
evaluate_every: 50
evaluation_steps: 100
greedy_p: 0
env:
  max_steps: 50
  split_coins: False
  grid_size: 3
base_agent:
  gamma: 0.95
  opt_type: "eg"
vip_agent:
  optim_config:
    lr: 0.00001
    momentum: 0.9
    weight_decay: 0
    beta_1: 0.9
    beta_2: 0.999
  batch_size: 2800
  rollout_len: 50
  representation_size: 4
  hidden_size: 64
  history_len: 4
  collab_weight: 1
  exploit_weight: 1
  entropy_weight: 0